cura=gca;
axes('units','normal','position',[0 0 .4 .05],'visible','off')
h=text(0.0,0.0,'The Vibration Toolbox','color',[1 1 0],...
      'units','normalized','fontsize',10,...
	  'fontname','times','fontangle','ital','verticalalignment','bottom',...
	  'horizontalalignment','left','visible','on');
set(gcf,'currentaxes',cura);
